### ISSUE TITLE
protoc-gen-go not found on Linux

### ISSUE THREAD

**Issue by saweiss** [openfoxwq/openfoxwq#1]
I tried running the compile_protos.sh script to install on Linux, but I receive the following message:

```
protoc-gen-go: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--go_out: protoc-gen-go: Plugin failed with status code 1.
```

I couldn't seem to find the program this was referencing. Any ideas?

**Comment by ale64bit** [comment]
This refers to the [protobuf](https://protobuf.dev) Go plugin. You can find more information [here](https://protobuf.dev/getting-started/gotutorial/#compiling-protocol-buffers] on how to install it.

I'll try to build in a Linux VM today and write detailed instructions.

**Comment by ale64bit** [comment]
@saweiss I added some [build instructions](https://github.com/openfoxwq/openfoxwq#build-instructions). I also added prebuilt binaries for Linux in the same release, in case you want to try those directly.

**Comment by saweiss** [comment]
Thanks that helped. I had protobuf on the path, but for some reason it needed to be specifically the version installed with `go install` in `$GOPATH`.

**Comment by saweiss** [comment]
P.S. I had to change the path to libprotobuf in the makefile to `/usr/lib/libprotobuf.so' (no local and .so instead of .a) in order to compile.

**Comment by ale64bit** [comment]
Yep, there was the same issue here: https://github.com/openfoxwq/openfoxwq_qtclient/issues/1.
I'm trying to figure out how to add it to the .pro file so that it works in most installations. For some reason `LIBS += -lprotobuf` wasn't working properly.

**Comment by ale64bit** [comment]
I changed it a bit: https://github.com/openfoxwq/openfoxwq_qtclient/blob/main/openfoxwq_qtclient.pro#L78.
Let me know if this helps with avoiding manually modifying the .pro file.

**Comment by saweiss** [comment]
It's working now, thanks!
