### ISSUE TITLE
Server crashes with broken pipe on login

### ISSUE THREAD

**Issue by F0re** [openfoxwq/openfoxwq#7]
Here is the server log:
2023/03/01 12:50:45 serving...
2023/03/01 12:50:57 new connection
2023/03/01 12:50:57 creating fox client...
2023/03/01 12:50:57 getting navigation info...
2023/03/01 12:50:58 creating navigation client...
2023/03/01 12:50:58 getting server list...
2023/03/01 12:51:11 [ws] req: login:{ username:"F0re99" }
2023/03/01 12:51:12 [ws] req: getInitData:{}
2023/03/01 12:51:12 creating broadcast client...
2023/03/01 12:51:12 getting broadcast list...
2023/03/01 12:51:12 broadcast list resp 1/8: 50
2023/03/01 12:51:12 broadcast list resp 2/8: 50
2023/03/01 12:51:13 broadcast list resp 3/8: 50
2023/03/01 12:51:13 broadcast list resp 4/8: 50
2023/03/01 12:51:13 broadcast list resp 5/5: 17
2023/03/01 12:51:13 creating play client...
2023/03/01 12:51:13 listening to broadcast events...
2023/03/01 12:51:13 logging into play service...
2023/03/01 12:51:13 listing players...
2023/03/01 12:51:13 listening to player events...
2023/03/01 12:51:13 listening to game events...
2023/03/01 12:51:14 player list 1/17: 200
2023/03/01 12:51:14 player list 2/17: 200
2023/03/01 12:51:14 player list 3/17: 200
2023/03/01 12:51:15 player list 4/17: 200
2023/03/01 12:51:15 player list 5/17: 200
2023/03/01 12:51:15 player list 6/17: 200
2023/03/01 12:51:16 player list 7/17: 200
2023/03/01 12:51:16 player list 8/17: 200
2023/03/01 12:51:16 player list 9/17: 200
2023/03/01 12:51:16 player list 10/17: 200
2023/03/01 12:51:16 player list 11/17: 200
2023/03/01 12:51:16 player list 12/17: 200
2023/03/01 12:51:16 player list 13/17: 200
2023/03/01 12:51:16 unknown country: name="f0re99" code=358
2023/03/01 12:51:16 unknown country: name="twohome308" code=353
2023/03/01 12:51:16 unknown country: name="twohome307" code=353
2023/03/01 12:51:16 unknown country: name="twohome306" code=353
2023/03/01 12:51:17 player list 14/17: 200
2023/03/01 12:51:17 unknown country: name="newdouhand" code=420
2023/03/01 12:51:17 player list 15/17: 200
2023/03/01 12:51:17 unknown country: name="aoshii" code=54
2023/03/01 12:51:17 writing to websocket: writev tcp [::1]:8999->[::1]:61894: writev: broken pipe

**Comment by F0re** [comment]
Ok, this seems to happen only after I copied open foxwq_qtclient to Applications from folder on my Mac, but if I start with from inside the dmg then this issue doesn't occur.

**Comment by F0re** [comment]
I got it working one more time from the dmg but now it's failing with the same error even if I start it from within the dmg.

**Comment by F0re** [comment]
For some reason after I rebooted my Mac I got this to work again. Will have to see how this develops.

**Comment by F0re** [comment]
This time reboot didn't help and even after reboot the server is crashing with broken pipe.

**Comment by ale64bit** [comment]
Hi there. Thanks for reporting. Could you also provide the version you are using?

Actually, it looks like it's not the server which crashes, but the client. The server simply closes because it detects that the websocket connection with the client was closed. This looks like a similar issue as it was reported days ago in the [discord server](https://discord.gg/xuK3THud). Feel free to join. The problem seems to be related to some players having invalid utf-8 name or native name. If you haven't tried, try with the [v.0.3-alpha](https://github.com/openfoxwq/openfoxwq/releases/tag/v0.3-alpha) pre-release and let me know if you still encounter the same issue.

**Comment by F0re** [comment]
[v0.1-alpha](https://github.com/openfoxwq/openfoxwq/releases/tag/v0.1-alpha)
Since it was linked from: https://www.reddit.com/r/baduk/comments/10sv5ry/foxwq_reverse_engineering_and_open_client/
I'll try with 0.3. Thanks!
